spring:
  application:
    name: config-server
  security:
    user:
      name: configuser
      password: configPass$1234
  cloud:
    activate:
      on-profile: default
    config:
      server:
        git:
          uri: https://github.com/SadaLearningHub1/spring-boot-config-repo.git  # Replace with your repository URL
          default-label: main  # Use the main branch
#          force-pull: true # pull the latest code from GIT incase the local repo has some issues and couldn't able to update the repo
#          skipSslValidation: true # Git Server SSL validation can be disabled
#          timeout: 10 #HTTP connection timeout (In Seconds)
#          username: *****
#          password: ******
server:
  port: 8888
  
